name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - core-release

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to push to gh-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: kublade.org
